services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mnawatch
    ports:
      - "5432:5432"
    volumes:
      - mnawatch_pg:/var/lib/postgresql/data
volumes:
  mnawatch_pg:
